spring.application.name=order-service
server.port=${SERVER_PORT_ORDER} 
spring.datasource.url=jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.schemas=orders
spring.flyway.default-schema=orders
spring.flyway.create-schemas=true
spring.flyway.locations=classpath:db/migration

menu.service.url=${MENU_SERVICE_URL}
qr.service.url=${QR_SERVICE_URL}
